# Generated by Django 4.1.5 on 2023-07-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anuncios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="CategAnunciooria", new_name="Anuncio",),
    ]
